const express = require("express");
const fs = require("fs");
const path = require("path");
const { spawn, execFileSync } = require("child_process");
const crypto = require("crypto");

const { log, logPrefix, LOG_RING, stripAnsi } = require("./lib/logger");
const {
  API_TOKEN, TOKEN_IS_AUTOGEN, RATE_LIMIT_DISABLED, KILO_DIR,
  authGate, readLimiter, writeLimiter, authLimiter,
  inspectAuth, DEVICE_AUTH, runDeviceAuth,
} = require("./lib/auth");
const {
  REPOS_DIR, GIT_URL_RE, BRANCH_RE,
  loadSessions, saveSessions, updateStatus, terminateProcess, checkoutRepo, repoName,
} = require("./lib/sessions");
const { startKiloSession, initKiloStartup, scanInternalLogs, sendPromptToLive, isLive } = require("./lib/kilo");

const app = express();
app.set("trust proxy", 1);
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.disable("x-powered-by");

const PORT = parseInt(process.env.PORT || "7860", 10);

try { fs.mkdirSync(path.dirname("/data/sessions.json"), { recursive: true }); } catch (_) {}
try { fs.mkdirSync(REPOS_DIR, { recursive: true }); } catch (_) {}

let INDEX_HTML = "";
try { INDEX_HTML = fs.readFileSync(path.join(__dirname, "templates", "index.html"), "utf8"); } catch (_) {}

// Cache kilo version + path ONCE at boot. Previously /api/status shelled out to
// `kilo --version` and `kilo daemon status` on EVERY poll. The UI polls status
// frequently, so each poll spawned kilo processes that (a) flooded the internal
// log dir — kilo keeps only ~11 log files, so the live TUI session's log (with
// the ses_ cloud id + ingest breadcrumbs) got rotated out within a minute, and
// (b) caused lock contention with the live TUI. We no longer run a daemon (the
// TUI manages its own server/ingest/remote WebSocket), so daemon status is dead.
let KILO_VERSION = "unknown";
let KILO_WHICH = null;
try {
  KILO_WHICH = execFileSync("which", ["kilo"], { encoding: "utf8", timeout: 5000 }).trim();
} catch (_) {}
try {
  KILO_VERSION = execFileSync("kilo", ["--version"], { encoding: "utf8", timeout: 5000 }).trim().slice(0, 100);
} catch (_) {}
log(`boot kilo version=${KILO_VERSION} which=${KILO_WHICH || "not found"} (cached at boot — /api/status will NOT re-spawn kilo)`);

// ── Routes ───────────────────────────────────────────────────────

app.get("/", (_req, res) => {
  if (!INDEX_HTML) return res.status(500).send("index.html unavailable");
  const safe = API_TOKEN.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const html = INDEX_HTML.replace('<script>window.__HERMES_TOKEN__="";</script>', `<script>window.__HERMES_TOKEN__="${safe}";</script>`);
  res.set("Content-Type", "text/html; charset=utf-8");
  res.send(html);
});

app.get("/api/status", (_req, res) => {
  // NOTE: This must NOT spawn any kilo process. Version/path are cached at boot.
  // Spawning kilo per-poll floods the internal log dir (rotating out the live
  // TUI session log we need to scan) and causes TUI lock contention.
  const result = {
    kilo_version: KILO_VERSION,
    kilo_which: KILO_WHICH,
    daemon_running: false, // no daemon in this architecture — TUI self-manages
    auth_exists: false,
    repos_dir_exists: fs.existsSync(REPOS_DIR),
    session_count: loadSessions().length,
    default_model: null,
    small_model: null,
  };
  try {
    const cfg = JSON.parse(fs.readFileSync(path.join(KILO_DIR, "kilo.json"), "utf8"));
    result.default_model = cfg.model || null;
    result.small_model = cfg.small_model || null;
  } catch (_) {}
  try {
    const st = fs.statSync("/data/kilo/auth.json");
    if (st.size > 10) result.auth_exists = true;
  } catch (_) {}
  res.json({
    ...result,
    api_security: {
      token_required: true,
      token_autogenerated: TOKEN_IS_AUTOGEN,
      token_length: API_TOKEN.length,
      rate_limits: RATE_LIMIT_DISABLED ? "disabled" : {
        read_endpoints:  "60 / min / IP",
        write_endpoints: "10 / min / IP",
        auth_endpoints:  "20 / hour / IP",
      },
      proxy_aware: true,
    },
  });
});

app.get("/api/logs/session/:id", authGate, readLimiter, (req, res) => {
  try {
    const logFile = path.join(KILO_DIR, `session-${req.params.id}.log`);
    const raw = fs.readFileSync(logFile, "utf8");
    const clean = stripAnsi(raw);
    const lines = clean.split("\n").filter(Boolean).slice(-200);
    res.json({ lines, raw_length: raw.length, clean_length: clean.length });
  } catch (e) {
    res.json({ lines: [], error: e.message });
  }
});

app.get("/api/logs/kilo-internal", authGate, readLimiter, (_req, res) => {
  try {
    const logDir = path.join(KILO_DIR, "log");
    const files = fs.readdirSync(logDir);
    const result = {};
    for (const f of files) {
      try {
        const content = fs.readFileSync(path.join(logDir, f), "utf8");
        result[f] = content.split("\n").filter(Boolean).slice(-100);
      } catch (_) {}
    }
    res.json({ files: Object.keys(result), logs: result });
  } catch (e) {
    res.json({ files: [], logs: {}, error: e.message });
  }
});

app.get("/api/relay-check", authGate, readLimiter, async (_req, res) => {
  const auth = inspectAuth();

  let apiCheck = { reachable: null, http: null, error: null };
  try {
    const res = await fetch("https://api.kilo.ai/api/profile", {
      method: "GET",
      headers: auth.valid && auth.detected_type !== "env-var"
        ? { "Authorization": `Bearer ${auth.token ?? ""}` }
        : {},
      signal: AbortSignal.timeout(5000),
    });
    apiCheck = { reachable: true, http: res.status, error: null, verified: res.status === 200, auth_invalid: res.status === 401 };
  } catch (e) {
    apiCheck = { reachable: false, http: null, error: e.message };
  }

  let ingestCheck = { reachable: null, http: null, error: null };
  try {
    const res = await fetch("https://ingest.kilosessions.ai", { method: "GET", signal: AbortSignal.timeout(5000) });
    ingestCheck = { reachable: true, http: res.status, error: null };
  } catch (e) {
    ingestCheck = { reachable: false, http: null, error: e.message };
  }

  let generatedConfig = null;
  try {
    const cfgPath = path.join(KILO_DIR, "kilo.json");
    generatedConfig = JSON.parse(fs.readFileSync(cfgPath, "utf8"));
  } catch (_) {}

  let verdict;
  if (!auth.valid)          verdict = `BLOCKED: ${auth.reason}`;
  else if (!apiCheck.reachable) verdict = "BLOCKED: api.kilo.ai unreachable";
  else if (apiCheck.auth_invalid) verdict = "BLOCKED: api.kilo.ai rejected credentials (401) — re-auth required";
  else if (!ingestCheck.reachable) verdict = "BLOCKED: ingest.kilosessions.ai unreachable — relay will fail";
  else                       verdict = "OK: per-PTY session with KILO_REMOTE=1 will appear in Cloud Dashboard";

  res.json({
    verdict,
    auth: {
      file_exists: auth.file_exists,
      file_keys: auth.file_keys,
      configured_type: auth.configured_type,
      detected_type: auth.detected_type,
      valid: auth.valid,
      expired: auth.expired,
      reason: auth.reason,
    },
    api: apiCheck,
    ingest: ingestCheck,
    config: {
      primary_path: "/data/kilo/kilo.json",
      primary_contents: generatedConfig,
      legacy_path: "/data/kilo/config.json",
      remote_control: generatedConfig?.remote_control === true,
    },
    endpoints: {
      cloud_dashboard: "https://app.kilo.ai/cloud",
      api:            "https://api.kilo.ai",
      ingest:         "https://ingest.kilosessions.ai",
      websocket:      "wss://ingest.kilosessions.ai",
    },
    env: {
      KILO_API_KEY_set:    !!process.env.KILO_API_KEY,
      KILO_AUTH_TOKEN_set: !!process.env.KILO_AUTH_TOKEN,
      KILO_REMOTE:         process.env.KILO_REMOTE || null,
    },
  });
});

app.get("/api/diagnostics", authGate, readLimiter, async (_req, res) => {
  // Must NOT spawn kilo (no daemon in this architecture; spawning floods the
  // internal log dir and contends with the live TUI). Reports auth + the latest
  // kilo-sessions ingest/remote breadcrumbs scanned from the internal logs.
  const auth = inspectAuth();
  const diag = {
    daemon_running: false,
    auth_exists: false,
    auth_type: null,
    relay: {
      file_exists: auth.file_exists,
      file_keys: auth.file_keys,
      configured_type: auth.configured_type,
      detected_type: auth.detected_type,
      valid: auth.valid,
      expired: auth.expired,
      reason: auth.reason,
    },
  };
  try {
    const st = fs.statSync("/data/kilo/auth.json");
    if (st.size > 10) diag.auth_exists = true;
    const auth = JSON.parse(fs.readFileSync("/data/kilo/auth.json", "utf8"));
    diag.auth_type = auth?.kilo?.type || null;
  } catch (_) {}
  try {
    diag.internal_log_scan = scanInternalLogs(0);
  } catch (e) { diag.internal_log_scan_error = e.message; }
  res.json(diag);
});

app.get("/api/logs", authGate, readLimiter, (req, res) => {
  const n = parseInt(req.query.n || "200", 10);
  const lines = LOG_RING.slice(-n);
  res.json({ count: lines.length, lines });
});

app.get("/api/sessions", authGate, readLimiter, (_req, res) => {
  const sessions = updateStatus(loadSessions());
  try { saveSessions(sessions); }
  catch (e) { log(`_persist_sessions write failed (non-fatal): ${e.message}`); }
  res.json(sessions);
});

app.post("/api/spin-up", authGate, writeLimiter, async (req, res) => {
  const data = req.body || {};
  const repoUrl = (data.repo_url || "").trim();
  const branch = (data.branch || "").trim();

  if (!repoUrl) {
    return res.status(400).json({ error: "repo_url required" });
  }
  if (!GIT_URL_RE.test(repoUrl)) {
    return res.status(400).json({
      error: "repo_url must end in .git — e.g. https://github.com/owner/repo.git or git@github.com:owner/repo.git",
      received: repoUrl,
    });
  }
  if (!branch) {
    return res.status(400).json({
      error: "branch required — pick the branch you want this session to work on (e.g. 'main')",
    });
  }
  if (!BRANCH_RE.test(branch)) {
    return res.status(400).json({
      error: "branch contains characters git cannot use as a ref name (spaces, ':', '..', '~', '^', etc. are forbidden)",
      received: branch,
    });
  }

  const sessionId = crypto.randomUUID().slice(0, 8);
  const repo = repoName(repoUrl);
  const label = sessionId;
  log(`spin-up session=${label} repo=${repo} branch=${branch}`);

  let workDir;
  try {
    const result = checkoutRepo(repoUrl, branch, sessionId);
    workDir = result.workDir;
  } catch (e) {
    return res.status(500).json({ error: "clone failed \u2014 check repo URL and access permissions" });
  }

  let result;
  try {
    result = await startKiloSession(workDir, label);
  } catch (e) {
    return res.status(500).json({ error: `session start failed: ${e.message}` });
  }
  const { pid: kiloPid, cloudSessionId } = result;

  const session = {
    id: sessionId,
    repo_url: repoUrl,
    repo_name: repo,
    branch,
    work_dir: workDir,
    pid: kiloPid,
    cloud_session_id: cloudSessionId || null,
    status: "running",
    started_at: new Date().toISOString(),
  };

  const sessions = updateStatus(loadSessions());
  sessions.push(session);
  saveSessions(sessions);
  log(`spin-up ${logPrefix(label)} created id=${sessionId} pid=${kiloPid} branch=${branch}`);
  res.status(201).json(session);
});

app.post("/api/kill/:sessionId", authGate, writeLimiter, async (req, res) => {
  try {
    const sessions = updateStatus(loadSessions());
    for (const s of sessions) {
      if (s.id !== req.params.sessionId) continue;
      await terminateProcess(s.pid || 0);
      s.status = "killed";
      s.stopped_at = new Date().toISOString();
      saveSessions(sessions);

      const logFile = path.join(KILO_DIR, `session-${s.id}.log`);
      try { fs.unlinkSync(logFile); log(`kill ${logPrefix(s.id)} removed log ${logFile}`); } catch (_) {}
      if (s.work_dir && fs.existsSync(s.work_dir)) {
        try { fs.rmSync(s.work_dir, { recursive: true, force: true }); log(`kill ${logPrefix(s.id)} removed work_dir ${s.work_dir}`); } catch (_) {}
      }

      return res.json({ status: "killed", session_id: req.params.sessionId });
    }
    res.status(404).json({ error: "session not found" });
  } catch (e) {
    log(`kill ${logPrefix(req.params.sessionId)} error: ${e.message}`);
    res.status(500).json({ error: "failed to kill session" });
  }
});

app.post("/api/sessions/:id/pause", authGate, writeLimiter, async (req, res) => {
  try {
    const sessions = updateStatus(loadSessions());
    for (const s of sessions) {
      if (s.id !== req.params.id) continue;
      if (s.status !== "running") {
        return res.status(409).json({ error: "session is not running" });
      }
      await terminateProcess(s.pid || 0);
      s.status = "paused";
      s.paused_at = new Date().toISOString();
      s.pid = null;
      saveSessions(sessions);
      return res.json({ status: "paused", session_id: req.params.id });
    }
    res.status(404).json({ error: "session not found" });
  } catch (e) {
    log(`pause ${logPrefix(req.params.id)} error: ${e.message}`);
    res.status(500).json({ error: "failed to pause session" });
  }
});

app.post("/api/sessions/:id/continue", authGate, writeLimiter, (req, res) => {
  const prompt = (req.body?.prompt || "").trim();
  if (!prompt) {
    return res.status(400).json({ error: "prompt required in body" });
  }

  const sessions = loadSessions();
  const session = sessions.find((s) => s.id === req.params.id);
  if (!session) {
    return res.status(404).json({ error: "session not found" });
  }
  if (!session.cloud_session_id) {
    return res.status(409).json({
      error: "no cloud_session_id captured — original kilo run may still be in progress, or did not complete cleanly",
    });
  }
  if (session.status === "running") {
    return res.status(409).json({ error: "session is still running" });
  }

  const model = process.env.HERMES_DEFAULT_MODEL || "kilo/kilo-auto/free";
  const args = [
    "run",
    prompt,
    "--dir", session.work_dir,
    "--session", session.cloud_session_id,
    "--cloud-fork",
    "--share",
    "--dangerously-skip-permissions",
    "--model", model,
    "--print-logs",
    "--log-level", "INFO",
  ];

  const label = req.params.id;
  const logFile = path.join(KILO_DIR, `session-${label}-cont-${Date.now()}.log`);
  log(`_continue_session ${logPrefix(label)} cloud_id=${session.cloud_session_id} running: kilo ${args.join(" ")}`);
  const logFd = fs.openSync(logFile, "a");
  const child = spawn("kilo", args, {
    cwd: session.work_dir,
    env: { ...process.env, KILO_REMOTE: "1" },
    stdio: ["ignore", logFd, logFd],
    detached: true,
  });
  child.unref();

  session.status = "running";
  session.pid = child.pid;
  session.started_at = new Date().toISOString();
  session.last_continue_prompt = prompt.slice(0, 200);
  session.last_continue_log = logFile;
  saveSessions(sessions);

  return res.status(202).json({
    session_id: label,
    cloud_session_id: session.cloud_session_id,
    pid: child.pid,
    log_file: logFile,
    prompt_excerpt: prompt.slice(0, 200),
  });
});

app.post("/api/sessions/:id/resume", authGate, writeLimiter, (req, res) => {
  const sessions = loadSessions();
  const session = sessions.find((s) => s.id === req.params.id);
  if (!session) {
    return res.status(404).json({ error: "session not found" });
  }
  if (session.status === "running") {
    return res.status(409).json({ error: "session is already running" });
  }
  if (session.status === "killed") {
    return res.status(409).json({ error: "killed sessions cannot be resumed" });
  }
  if (!session.cloud_session_id) {
    return res.status(409).json({
      error: "no cloud_session_id captured — cannot resume this session",
    });
  }
  if (!session.work_dir || !fs.existsSync(session.work_dir)) {
    return res.status(409).json({
      error: "work directory no longer exists — cannot resume",
    });
  }

  const prompt = (req.body?.prompt || "").trim() || process.env.HERMES_INITIAL_PROMPT || "continue";
  const model = process.env.HERMES_DEFAULT_MODEL || "kilo/kilo-auto/free";
  const args = [
    "run",
    prompt,
    "--dir", session.work_dir,
    "--session", session.cloud_session_id,
    "--cloud-fork",
    "--share",
    "--dangerously-skip-permissions",
    "--model", model,
    "--print-logs",
    "--log-level", "INFO",
  ];

  const label = req.params.id;
  const logFile = path.join(KILO_DIR, `session-${label}-resume-${Date.now()}.log`);
  log(`_resume_session ${logPrefix(label)} cloud_id=${session.cloud_session_id} running: kilo ${args.join(" ")}`);
  const logFd = fs.openSync(logFile, "a");
  const child = spawn("kilo", args, {
    cwd: session.work_dir,
    env: { ...process.env, KILO_REMOTE: "1" },
    stdio: ["ignore", logFd, logFd],
    detached: true,
  });
  child.unref();

  child.on("exit", (code) => {
    log(`_monitor_resume ${logPrefix(label)} kilo run exited code=${code}`);
    const all = loadSessions();
    for (const s of all) {
      if (s.id === label && s.status === "running") {
        s.status = "stopped";
        s.stopped_at = new Date().toISOString();
        s.exit_code = code;
      }
    }
    saveSessions(all);
  });

  session.status = "running";
  session.pid = child.pid;
  session.started_at = new Date().toISOString();
  session.resume_count = (session.resume_count || 0) + 1;
  session.resume_log = logFile;
  saveSessions(sessions);

  return res.status(202).json({
    session_id: label,
    cloud_session_id: session.cloud_session_id,
    pid: child.pid,
    log_file: logFile,
    prompt_excerpt: prompt.slice(0, 200),
  });
});

app.post("/api/auth/login", authLimiter, (req, res) => {
  if (DEVICE_AUTH.status === "pending") {
    return res.json({
      status: DEVICE_AUTH.status,
      url: DEVICE_AUTH.url,
      code: DEVICE_AUTH.code,
      message: DEVICE_AUTH.message,
    });
  }
  DEVICE_AUTH.status = "idle";
  DEVICE_AUTH.url = null;
  DEVICE_AUTH.code = null;
  DEVICE_AUTH.message = null;
  runDeviceAuth().then((result) => {
    if (result.success) {
      const authCheck = inspectAuth();
      log(`_run_device_auth auth probe: valid=${authCheck.valid} type=${authCheck.detected_type} reason=${authCheck.reason}`);
      if (authCheck.valid) {
        log("_run_device_auth auth valid — TUI sessions will auto-connect to cloud via KILO_REMOTE=1 + remote_control=true");
      }
    }
  });

  res.json({
    status: DEVICE_AUTH.status,
    url: DEVICE_AUTH.url,
    code: DEVICE_AUTH.code,
    message: DEVICE_AUTH.message,
  });
});

app.get("/api/auth/status", authLimiter, (_req, res) => {
  res.json({
    status: DEVICE_AUTH.status,
    url: DEVICE_AUTH.url,
    code: DEVICE_AUTH.code,
    message: DEVICE_AUTH.message,
  });
});

app.post("/api/auth/cancel", authLimiter, (_req, res) => {
  DEVICE_AUTH.status = "cancelled";
  DEVICE_AUTH.message = "Login cancelled";
  if (DEVICE_AUTH.ptyProcess) {
    try { DEVICE_AUTH.ptyProcess.kill(); } catch (_) {}
  }
  DEVICE_AUTH.ptyProcess = null;
  res.json({ status: "cancelled" });
});

app.listen(PORT, "0.0.0.0", () => {
  log(`Server running on http://0.0.0.0:${PORT}`);
  initKiloStartup();
});