const express = require("express");
const fs = require("fs");
const path = require("path");
const { spawn, execFileSync } = require("child_process");

const { log, logPrefix, LOG_RING, stripAnsi } = require("./lib/logger");
const {
  API_TOKEN, TOKEN_IS_AUTOGEN, RATE_LIMIT_DISABLED, KILO_DIR,
  authGate, readLimiter, writeLimiter, authLimiter,
  inspectAuth, DEVICE_AUTH, runDeviceAuth,
} = require("./lib/auth");
const reposLib = require("./lib/repos");
const { REPOS_DIR, GIT_URL_RE, BRANCH_RE } = reposLib;
const kiloLib = require("./lib/kilo");
const { initKiloStartup, scanInternalLogs, sendPromptToLive, isLive, writeProjectConfig } = kiloLib;

const app = express();
app.set("trust proxy", 1);
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.disable("x-powered-by");

const PORT = parseInt(process.env.PORT || "7860", 10);

try { fs.mkdirSync(path.dirname("/data/repos.json"), { recursive: true }); } catch (_) {}
try { fs.mkdirSync(REPOS_DIR, { recursive: true }); } catch (_) {}

let INDEX_HTML = "";
try { INDEX_HTML = fs.readFileSync(path.join(__dirname, "templates", "index.html"), "utf8"); } catch (_) {}

// Cache kilo version + path ONCE at boot. Previously /api/status shelled out
// to `kilo --version` and `kilo daemon status` on EVERY poll. The UI polls
// status frequently, so each poll spawned kilo processes that flooded the
// internal log dir (rotating out the live TUI session log we need to scan).
let KILO_VERSION = "unknown";
let KILO_WHICH = null;
try {
  KILO_WHICH = execFileSync("which", ["kilo"], { encoding: "utf8", timeout: 5000 }).trim();
} catch (_) {}
try {
  KILO_VERSION = execFileSync("kilo", ["--version"], { encoding: "utf8", timeout: 5000 }).trim().slice(0, 100);
} catch (_) {}
log(`boot kilo version=${KILO_VERSION} which=${KILO_WHICH || "not found"} (cached at boot — /api/status will NOT re-spawn kilo)`);

// ── Small helpers ────────────────────────────────────────────────────

// Q6: Auth pre-flight check. Returns a 409-ready error body if auth is
// invalid, otherwise null. Used by checkout / start / new-session so we
// never spawn a kilo PTY that's destined to die at the cloud-provider
// validation step (root cause of the original 361ce879/21:44 incident).
function authPreflight() {
  const auth = inspectAuth();
  if (!auth.valid) {
    return {
      error: `auth invalid — complete login on the Auth tab first (reason: ${auth.reason})`,
      auth_invalid: true,
    };
  }
  return null;
}

// ── Routes ───────────────────────────────────────────────────────────

app.get("/", (_req, res) => {
  if (!INDEX_HTML) return res.status(500).send("index.html unavailable");
  const safe = API_TOKEN.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const html = INDEX_HTML.replace('<script>window.__AGENT_DOCK_TOKEN__="";</script>', `<script>window.__AGENT_DOCK_TOKEN__="${safe}";</script>`);
  res.set("Content-Type", "text/html; charset=utf-8");
  res.send(html);
});

app.get("/health", (_req, res) => res.status(200).send("ok"));

app.get("/api/status", (_req, res) => {
  // NOTE: This must NOT spawn any kilo process. Version/path are cached at
  // boot (spawning flood-rotates the live TUI log we scan for the cloud id).
  const result = {
    kilo_version: KILO_VERSION,
    kilo_which: KILO_WHICH,
    daemon_running: false,
    auth_exists: false,
    repos_dir_exists: fs.existsSync(REPOS_DIR),
    repo_count: reposLib.loadRepos().length,
    default_model: null,
    small_model: null,
  };
  try {
    const cfg = JSON.parse(fs.readFileSync(path.join(KILO_DIR, "kilo.json"), "utf8"));
    result.default_model = cfg.model || null;
    result.small_model = cfg.small_model || null;
  } catch (_) {}
  try {
    const st = fs.statSync("/data/kilo/auth.json");
    if (st.size > 10) result.auth_exists = true;
  } catch (_) {}
  res.json({
    ...result,
    api_security: {
      token_required: true,
      token_autogenerated: TOKEN_IS_AUTOGEN,
      token_length: API_TOKEN.length,
      rate_limits: RATE_LIMIT_DISABLED ? "disabled" : {
        read_endpoints:  "60 / min / IP",
        write_endpoints: "10 / min / IP",
        auth_endpoints:  "20 / hour / IP",
      },
      proxy_aware: true,
    },
  });
});

app.get("/api/logs/session/:id", authGate, readLimiter, async (req, res) => {
  try {
    // `id` is the bucket work_dir_identifier (e.g. "xyz"), not a session id.
    const logFile = path.join(KILO_DIR, `session-${req.params.id}.log`);
    const raw = await fs.promises.readFile(logFile, "utf8");
    const clean = stripAnsi(raw);
    const lines = clean.split("\n").filter(Boolean).slice(-200);
    res.json({ lines, raw_length: raw.length, clean_length: clean.length });
  } catch (e) {
    res.json({ lines: [], error: e.message });
  }
});

app.get("/api/logs/kilo-internal", authGate, readLimiter, async (_req, res) => {
  try {
    const logDir = path.join(KILO_DIR, "log");
    const files = await fs.promises.readdir(logDir);
    const result = {};
    for (const f of files) {
      try {
        const content = await fs.promises.readFile(path.join(logDir, f), "utf8");
        result[f] = content.split("\n").filter(Boolean).slice(-100);
      } catch (_) {}
    }
    res.json({ files: Object.keys(result), logs: result });
  } catch (e) {
    res.json({ files: [], logs: {}, error: e.message });
  }
});

app.get("/api/relay-check", authGate, readLimiter, async (_req, res) => {
  const auth = inspectAuth();

  let apiCheck = { reachable: null, http: null, error: null };
  try {
    const res = await fetch("https://api.kilo.ai/api/profile", {
      method: "GET",
      headers: auth.valid && auth.detected_type !== "env-var"
        ? { "Authorization": `Bearer ${auth.token ?? ""}` }
        : {},
      signal: AbortSignal.timeout(5000),
    });
    apiCheck = { reachable: true, http: res.status, error: null, verified: res.status === 200, auth_invalid: res.status === 401 };
  } catch (e) {
    apiCheck = { reachable: false, http: null, error: e.message };
  }

  let ingestCheck = { reachable: null, http: null, error: null };
  try {
    const res = await fetch("https://ingest.kilosessions.ai", { method: "GET", signal: AbortSignal.timeout(5000) });
    ingestCheck = { reachable: true, http: res.status, error: null };
  } catch (e) {
    ingestCheck = { reachable: false, http: null, error: e.message };
  }

  let generatedConfig = null;
  try {
    const cfgPath = path.join(KILO_DIR, "kilo.json");
    generatedConfig = JSON.parse(fs.readFileSync(cfgPath, "utf8"));
  } catch (_) {}

  let verdict;
  if (!auth.valid)               verdict = `BLOCKED: ${auth.reason}`;
  else if (!apiCheck.reachable)  verdict = "BLOCKED: api.kilo.ai unreachable";
  else if (apiCheck.auth_invalid) verdict = "BLOCKED: api.kilo.ai rejected credentials (401) — re-auth required";
  else if (!ingestCheck.reachable) verdict = "BLOCKED: ingest.kilosessions.ai unreachable — relay will fail";
  else                          verdict = "OK: per-PTY session with KILO_REMOTE=1 will appear in Cloud Dashboard";

  res.json({
    verdict,
    auth: {
      file_exists: auth.file_exists,
      file_keys: auth.file_keys,
      configured_type: auth.configured_type,
      detected_type: auth.detected_type,
      valid: auth.valid,
      expired: auth.expired,
      reason: auth.reason,
    },
    api: apiCheck,
    ingest: ingestCheck,
    config: {
      primary_path: "/data/kilo/kilo.json",
      primary_contents: generatedConfig,
      legacy_path: "/data/kilo/config.json",
      remote_control: generatedConfig?.remote_control === true,
    },
    endpoints: {
      cloud_dashboard: "https://app.kilo.ai/cloud",
      api:            "https://api.kilo.ai",
      ingest:         "https://ingest.kilosessions.ai",
      websocket:      "wss://ingest.kilosessions.ai",
    },
    env: {
      KILO_API_KEY_set:    !!process.env.KILO_API_KEY,
      KILO_AUTH_TOKEN_set: !!process.env.KILO_AUTH_TOKEN,
      KILO_REMOTE:         process.env.KILO_REMOTE || null,
    },
  });
});

app.get("/api/diagnostics", authGate, readLimiter, async (_req, res) => {
  const auth = inspectAuth();
  const diag = {
    daemon_running: false,
    auth_exists: false,
    auth_type: null,
    relay: {
      file_exists: auth.file_exists,
      file_keys: auth.file_keys,
      configured_type: auth.configured_type,
      detected_type: auth.detected_type,
      valid: auth.valid,
      expired: auth.expired,
      reason: auth.reason,
    },
  };
  try {
    const st = fs.statSync("/data/kilo/auth.json");
    if (st.size > 10) diag.auth_exists = true;
    const auth = JSON.parse(fs.readFileSync("/data/kilo/auth.json", "utf8"));
    diag.auth_type = auth?.kilo?.type || null;
  } catch (_) {}
  try {
    diag.internal_log_scan = scanInternalLogs(0);
  } catch (e) { diag.internal_log_scan_error = e.message; }
  res.json(diag);
});

app.get("/api/logs", authGate, readLimiter, (req, res) => {
  const n = parseInt(req.query.n || "200", 10);
  const lines = LOG_RING.slice(-n);
  res.json({ count: lines.length, lines });
});

// ── Repo bucket endpoints (replaces old /api/sessions* and /api/spin-up) ──

app.get("/api/repos", authGate, readLimiter, (_req, res) => {
  const repos = reposLib.updateStatus(reposLib.loadRepos());
  try { reposLib.saveRepos(repos); }
  catch (e) { log(`_persist_repos write failed (non-fatal): ${e.message}`); }
  res.json(repos);
});

app.get("/api/repos/:workDirId", authGate, readLimiter, (req, res) => {
  const repos = reposLib.updateStatus(reposLib.loadRepos());
  const bucket = reposLib.findBucket(repos, req.params.workDirId);
  if (!bucket) return res.status(404).json({ error: "repo bucket not found" });
  res.json(bucket);
});

// POST /api/repos/checkout — clones the repo into /data/repos/<repo> and
// spawns a fresh kilo TUI session in it. Idempotent re-checkout returns 409
// "already checked out"; collision against a different repo_url returns 409
// "bucket collision — different repo_url".
app.post("/api/repos/checkout", authGate, writeLimiter, async (req, res) => {
  const data = req.body || {};
  const repoUrl = (data.repo_url || "").trim();
  const branch = (data.branch || "").trim() || "main";

  if (!repoUrl) return res.status(400).json({ error: "repo_url required" });
  if (!GIT_URL_RE.test(repoUrl)) {
    return res.status(400).json({
      error: "repo_url must end in .git — e.g. https://github.com/owner/repo.git or git@github.com:owner/repo.git",
      received: repoUrl,
    });
  }
  if (!BRANCH_RE.test(branch)) {
    return res.status(400).json({
      error: "branch contains characters git cannot use as a ref name (spaces, ':', '..', '~', '^', etc. are forbidden)",
      received: branch,
    });
  }

  const pre = authPreflight();
  if (pre) return res.status(409).json(pre);

  const workDirId = reposLib.bucketIdentifier(repoUrl);

  const existing = reposLib.findBucket(reposLib.loadRepos(), workDirId);
  if (existing) {
    if (existing.repo_url !== repoUrl) {
      log(`checkout ${logPrefix(workDirId)} BUCKET COLLISION — incoming ${repoUrl} vs existing ${existing.repo_url}`);
      return res.status(409).json({
        error: "bucket collision — different repo_url",
        work_dir_identifier: workDirId,
        existing_repo_url: existing.repo_url,
      });
    }
    log(`checkout ${logPrefix(workDirId)} already checked out (state=${existing.session_state})`);
    return res.status(409).json({
      error: "already checked out",
      work_dir_identifier: workDirId,
      session_state: existing.session_state,
      branch: existing.branch,
    });
  }

  let workDir;
  try {
    const result = reposLib.checkoutRepo(repoUrl, branch, workDirId);
    workDir = result.workDir;
  } catch (e) {
    return res.status(500).json({ error: "clone failed — check repo URL and access permissions" });
  }

  let result;
  try {
    result = await kiloLib.startKiloSession(workDir, workDirId);
  } catch (e) {
    return res.status(500).json({ error: `session start failed: ${e.message}` });
  }
  const { pid: kiloPid, cloudSessionId } = result;

  const bucket = reposLib.newBucket({ repoUrl, branch, workDir, workDirId });
  bucket.pid = kiloPid;
  bucket.kilo_session_id = cloudSessionId || null;
  bucket.is_active_in_agent_dock = true;
  bucket.cloud_session_status = cloudSessionId ? "active" : "unknown";
  if (result.started === false) {
    bucket.session_state = "stopped";
    bucket.stopped_at = new Date().toISOString();
    bucket.is_active_in_agent_dock = false;
    bucket.last_warning = result.reason || "kilo session did not reach an interactive prompt";
    log(`checkout ${logPrefix(workDirId)} WARNING — kilo did NOT confirm a created cloud session (reason=${result.reason})`);
  }

  const repos = reposLib.updateStatus(reposLib.loadRepos());
  // updateStatus may transit a stale stale running→stopped for an unrelated
  // bucket; don't accidentally re-push the bucket we're inserting via that.
  // Replace any existing entry with the same id just in case (it shouldn't
  // exist — we checked above — but a concurrent checkout race in the same
  // poll cycle could surface).
  const without = repos.filter((r) => r.work_dir_identifier !== workDirId);
  without.push(bucket);
  reposLib.saveRepos(without);
  log(`checkout ${logPrefix(workDirId)} created pid=${kiloPid} kilo_session_id=${bucket.kilo_session_id || "none"}`);

  res.status(201).json({
    work_dir_identifier: bucket.work_dir_identifier,
    repo_name: bucket.repo_name,
    branch: bucket.branch,
    work_dir: bucket.work_dir,
    kilo_session_id: bucket.kilo_session_id,
    pid: bucket.pid,
    session_state: bucket.session_state,
    is_active_in_agent_dock: bucket.is_active_in_agent_dock,
    last_warning: bucket.last_warning,
  });
});

// POST /api/repos/:workDirId/start — smart Start button.
// If a kilo_session_id is present, attempts resume (--session --cloud-fork).
// If resume reports importFailed (cloud session was deleted), the server
// falls through transparently to fresh-spawn behavior: returns 409 with
// `needs_new_session:true` so the UI can show the confirmation dialog; the
// user's confirmation triggers a follow-up call to /new-session.
// If no kilo_session_id, returns 409 needs_new_session right away.
app.post("/api/repos/:workDirId/start", authGate, writeLimiter, async (req, res) => {
  const repos = reposLib.updateStatus(reposLib.loadRepos());
  const bucket = reposLib.findBucket(repos, req.params.workDirId);
  if (!bucket) return res.status(404).json({ error: "repo bucket not found" });
  if (bucket.session_state === "running") {
    return res.status(409).json({ error: "already running", work_dir_identifier: bucket.work_dir_identifier });
  }
  if (!bucket.work_dir || !fs.existsSync(bucket.work_dir)) {
    return res.status(409).json({ error: "work directory no longer exists — cannot start" });
  }

  const pre = authPreflight();
  if (pre) return res.status(409).json(pre);

  // No cloud session on record → need a fresh spawn.
  if (!bucket.kilo_session_id) {
    return res.status(409).json({
      needs_new_session: true,
      reason: "no cloud session on record — start a new session in this work dir?",
      work_dir_identifier: bucket.work_dir_identifier,
    });
  }

  let result;
  try {
    result = await kiloLib.resumeKiloSession(bucket.work_dir, bucket.work_dir_identifier, bucket.kilo_session_id);
  } catch (e) {
    return res.status(500).json({ error: `resume failed: ${e.message}` });
  }

  // Cloud session was actually deleted even though we believed it was alive.
  // Surface needs_new_session so the UI asks for confirmation before we
  // silently start a brand-new kilo session in the work dir.
  if (result.importFailed) {
    bucket.cloud_session_status = "deleted";
    bucket.cloud_session_deleted = true;
    reposLib.saveRepos(repos);
    log(`start ${logPrefix(bucket.work_dir_identifier)} cloud session ${bucket.kilo_session_id} was deleted — needs_new_session`);
    return res.status(409).json({
      needs_new_session: true,
      reason: "cloud session no longer exists — start a new session in this work dir?",
      work_dir_identifier: bucket.work_dir_identifier,
      cloud_session_deleted: true,
    });
  }

  const { pid, cloudSessionId } = result;
  bucket.session_state = "running";
  bucket.pid = pid;
  bucket.is_active_in_agent_dock = true;
  if (cloudSessionId) bucket.kilo_session_id = cloudSessionId;
  bucket.cloud_session_status = "active";
  bucket.resumed_at = new Date().toISOString();
  bucket.resume_count = (bucket.resume_count || 0) + 1;
  bucket.last_warning = result.started === true ? null : (result.reason || "resume did not reach an interactive TUI");
  reposLib.saveRepos(repos);

  return res.status(result.started === true ? 202 : 200).json({
    work_dir_identifier: bucket.work_dir_identifier,
    kilo_session_id: bucket.kilo_session_id,
    pid,
    session_state: bucket.session_state,
    resumed_live: result.started === true,
    reason: result.reason || null,
  });
});

// POST /api/repos/:workDirId/new-session — explicit fresh spawn (no
// --session resume). Always creates a new kilo session in the existing work
// dir. Called by the UI after the "needs new session" confirmation dialog.
app.post("/api/repos/:workDirId/new-session", authGate, writeLimiter, async (req, res) => {
  const repos = reposLib.updateStatus(reposLib.loadRepos());
  const bucket = reposLib.findBucket(repos, req.params.workDirId);
  if (!bucket) return res.status(404).json({ error: "repo bucket not found" });
  if (bucket.session_state === "running") {
    return res.status(409).json({ error: "already running", work_dir_identifier: bucket.work_dir_identifier });
  }
  if (!bucket.work_dir || !fs.existsSync(bucket.work_dir)) {
    return res.status(409).json({ error: "work directory no longer exists — cannot start" });
  }

  const pre = authPreflight();
  if (pre) return res.status(409).json(pre);

  let result;
  try {
    result = await kiloLib.startKiloSession(bucket.work_dir, bucket.work_dir_identifier);
  } catch (e) {
    return res.status(500).json({ error: `session start failed: ${e.message}` });
  }
  const { pid: kiloPid, cloudSessionId } = result;

  bucket.session_state = result.started === false ? "stopped" : "running";
  if (result.started === false) {
    bucket.stopped_at = new Date().toISOString();
    bucket.last_warning = result.reason || "kilo did not reach an interactive prompt";
  } else {
    bucket.stopped_at = null;
    bucket.last_warning = null;
  }
  bucket.pid = kiloPid;
  bucket.kilo_session_id = cloudSessionId || bucket.kilo_session_id;
  bucket.is_active_in_agent_dock = result.started !== false;
  bucket.cloud_session_status = cloudSessionId ? "active" : "deleted";
  bucket.cloud_session_deleted = false;
  bucket.started_at = new Date().toISOString();
  bucket.resumed_at = new Date().toISOString();
  bucket.resume_count = (bucket.resume_count || 0) + 1;
  reposLib.saveRepos(repos);

  log(`new-session ${logPrefix(bucket.work_dir_identifier)} spawned pid=${kiloPid} kilo_session_id=${bucket.kilo_session_id || "none"} live=${result.started !== false}`);

  res.status(result.started === false ? 200 : 202).json({
    work_dir_identifier: bucket.work_dir_identifier,
    kilo_session_id: bucket.kilo_session_id,
    pid: kiloPid,
    session_state: bucket.session_state,
    is_active_in_agent_dock: bucket.is_active_in_agent_dock,
    last_warning: bucket.last_warning,
  });
});

// POST /api/repos/:workDirId/pause — kill PTY, keep cloud session alive.
app.post("/api/repos/:workDirId/pause", authGate, writeLimiter, async (req, res) => {
  const repos = reposLib.updateStatus(reposLib.loadRepos());
  const bucket = reposLib.findBucket(repos, req.params.workDirId);
  if (!bucket) return res.status(404).json({ error: "repo bucket not found" });
  if (bucket.session_state !== "running") {
    return res.status(409).json({ error: "bucket is not running" });
  }
  await reposLib.terminateProcess(bucket.pid || 0);
  bucket.session_state = "paused";
  bucket.paused_at = new Date().toISOString();
  bucket.pid = null;
  bucket.is_active_in_agent_dock = false;
  reposLib.saveRepos(repos);
  log(`pause ${logPrefix(bucket.work_dir_identifier)} — PTY killed, cloud_session_id ${bucket.kilo_session_id || "none"} preserved`);
  return res.status(200).json({ session_state: "paused", work_dir_identifier: bucket.work_dir_identifier });
});

// POST /api/repos/:workDirId/continue — headless one-shot `kilo run` against
// the bucket's cloud session id (no TUI). No UI button; for external callers.
app.post("/api/repos/:workDirId/continue", authGate, writeLimiter, (req, res) => {
  const prompt = (req.body?.prompt || "").trim();
  if (!prompt) return res.status(400).json({ error: "prompt required in body" });

  const repos = reposLib.loadRepos();
  const bucket = reposLib.findBucket(repos, req.params.workDirId);
  if (!bucket) return res.status(404).json({ error: "repo bucket not found" });
  if (!bucket.kilo_session_id) {
    return res.status(409).json({
      error: "no kilo_session_id on this bucket — start a session first via /start or /new-session",
    });
  }
  if (bucket.session_state === "running") {
    return res.status(409).json({ error: "session is already running — pause or use the TUI instead" });
  }

  const args = [
    "run", prompt,
    "--dir", bucket.work_dir,
    "--session", bucket.kilo_session_id,
    "--cloud-fork",
    "--share",
    "--dangerously-skip-permissions",
    "--print-logs",
    "--log-level", "INFO",
  ];

  writeProjectConfig(bucket.work_dir, bucket.work_dir_identifier);
  const logFile = path.join(KILO_DIR, `session-${bucket.work_dir_identifier}-cont-${Date.now()}.log`);
  log(`_continue ${logPrefix(bucket.work_dir_identifier)} cloud_id=${bucket.kilo_session_id} running: kilo ${args.join(" ")}`);
  const logFd = fs.openSync(logFile, "a");
  const child = spawn("kilo", args, {
    cwd: bucket.work_dir,
    env: {
      ...process.env,
      KILO_REMOTE: "1",
      // Permanent snapshot disable — see lib/kilo.js startKiloSession for
      // full rationale. KILO_CONFIG_CONTENT has highest config priority and
      // overrides all config files, so "Initializing snapshot…" never fires.
      KILO_CONFIG_CONTENT: JSON.stringify({ snapshot: false }),
    },
    stdio: ["ignore", logFd, logFd],
    detached: true,
  });
  child.unref();

  bucket.last_continue_prompt = prompt.slice(0, 200);
  bucket.last_continue_log = logFile;
  reposLib.saveRepos(repos);

  return res.status(202).json({
    work_dir_identifier: bucket.work_dir_identifier,
    kilo_session_id: bucket.kilo_session_id,
    pid: child.pid,
    log_file: logFile,
    prompt_excerpt: prompt.slice(0, 200),
  });
});

// POST /api/repos/:workDirId/kill — terminate PTY + delete cloud session,
// PRESERVE work_dir + registry entry. Status transitions to "killed".
app.post("/api/repos/:workDirId/kill", authGate, writeLimiter, async (req, res) => {
  const repos = reposLib.updateStatus(reposLib.loadRepos());
  const bucket = reposLib.findBucket(repos, req.params.workDirId);
  if (!bucket) return res.status(404).json({ error: "repo bucket not found" });

  await reposLib.terminateProcess(bucket.pid || 0);
  if (bucket.kilo_session_id) {
    const r = reposLib.deleteCloudSession(bucket.kilo_session_id);
    log(`kill ${logPrefix(bucket.work_dir_identifier)} cloud delete ok=${r.ok} reason=${r.reason}`);
  }
  bucket.session_state = "killed";
  bucket.killed_at = new Date().toISOString();
  bucket.pid = null;
  bucket.is_active_in_agent_dock = false;
  reposLib.saveRepos(repos);
  log(`kill ${logPrefix(bucket.work_dir_identifier)} — work dir preserved at ${bucket.work_dir}`);
  return res.status(200).json({
    session_state: "killed",
    work_dir_identifier: bucket.work_dir_identifier,
    work_dir_preserved: true,
  });
});

// DELETE /api/repos/:workDirId — kill + remove work dir + remove registry
// entry. The bucket can be re-checked-out fresh afterwards.
app.delete("/api/repos/:workDirId", authGate, writeLimiter, async (req, res) => {
  const repos = reposLib.updateStatus(reposLib.loadRepos());
  const bucket = reposLib.findBucket(repos, req.params.workDirId);
  if (!bucket) return res.status(404).json({ error: "repo bucket not found" });

  await reposLib.terminateProcess(bucket.pid || 0);
  if (bucket.kilo_session_id) {
    const r = reposLib.deleteCloudSession(bucket.kilo_session_id);
    log(`delete ${logPrefix(bucket.work_dir_identifier)} cloud delete ok=${r.ok} reason=${r.reason}`);
  }
  if (bucket.work_dir && fs.existsSync(bucket.work_dir)) {
    try { fs.rmSync(bucket.work_dir, { recursive: true, force: true }); } catch (e) {
      log(`delete ${logPrefix(bucket.work_dir_identifier)} work dir rm failed: ${e.message}`);
    }
  }
  // Also remove the per-session kilo PTY log file (orphan otherwise).
  const logFile = path.join(KILO_DIR, `session-${bucket.work_dir_identifier}.log`);
  try { fs.unlinkSync(logFile); log(`delete ${logPrefix(bucket.work_dir_identifier)} removed log ${logFile}`); } catch (_) {}

  const remaining = repos.filter((r) => r.work_dir_identifier !== bucket.work_dir_identifier);
  reposLib.saveRepos(remaining);
  log(`delete ${logPrefix(bucket.work_dir_identifier)} — work dir + registry entry removed`);
  return res.status(200).json({
    deleted: true,
    work_dir_identifier: bucket.work_dir_identifier,
  });
});

// ── Auth endpoints (unchanged) ───────────────────────────────────────

app.post("/api/auth/login", authLimiter, (req, res) => {
  if (DEVICE_AUTH.status === "pending") {
    return res.json({
      status: DEVICE_AUTH.status,
      url: DEVICE_AUTH.url,
      code: DEVICE_AUTH.code,
      message: DEVICE_AUTH.message,
    });
  }
  DEVICE_AUTH.status = "idle";
  DEVICE_AUTH.url = null;
  DEVICE_AUTH.code = null;
  DEVICE_AUTH.message = null;
  runDeviceAuth().then((result) => {
    if (result.success) {
      const authCheck = inspectAuth();
      log(`_run_device_auth auth probe: valid=${authCheck.valid} type=${authCheck.detected_type} reason=${authCheck.reason}`);
      if (authCheck.valid) {
        log("_run_device_auth auth valid — TUI sessions will auto-connect to cloud via KILO_REMOTE=1 + remote_control=true");
      }
    }
  });

  res.json({
    status: DEVICE_AUTH.status,
    url: DEVICE_AUTH.url,
    code: DEVICE_AUTH.code,
    message: DEVICE_AUTH.message,
  });
});

app.get("/api/auth/status", authLimiter, (_req, res) => {
  res.json({
    status: DEVICE_AUTH.status,
    url: DEVICE_AUTH.url,
    code: DEVICE_AUTH.code,
    message: DEVICE_AUTH.message,
  });
});

app.post("/api/auth/cancel", authLimiter, (_req, res) => {
  DEVICE_AUTH.status = "cancelled";
  DEVICE_AUTH.message = "Login cancelled";
  if (DEVICE_AUTH.ptyProcess) {
    try { DEVICE_AUTH.ptyProcess.kill(); } catch (_) {}
  }
  DEVICE_AUTH.ptyProcess = null;
  res.json({ status: "cancelled" });
});

module.exports = app;

if (require.main === module) {
  app.listen(PORT, "0.0.0.0", () => {
    log(`Server running on http://0.0.0.0:${PORT}`);
    initKiloStartup();
  });
}
